### ISSUE TITLE
Cannot Submit request for new place (state) to redistrict

### ISSUE THREAD

**Issue by cbradyatinquire** [districtr/districtr#129]
On the live districtr.org website, a group of us (hoping to use the site in a Math Teachers' Circle activity in early January), have been unable to add a request for Tennessee.  
It looks like this might be a general problem, as it has occurred for several of us on different networks.  
A screenshot is below, as is a copy paste of the error from the JavaScript console (using Chrome)

﻿
api.districtr.org/requests/:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
﻿
​
<img width="355" alt="Screen Shot 2019-11-25 at 8 35 29 AM" src="https://user-images.githubusercontent.com/769072/69549494-06495380-0f5f-11ea-9783-301b07545bc5.png">

**Comment by cbradyatinquire** [comment]
(the same problem occurs on Safari and Firefox).

**Comment by mapmeld** [comment]
Our form is back online. Thanks @cbradyatinquire for your report!
