### ISSUE TITLE
NC Congressional not committing changes.

### ISSUE THREAD

**Issue by Idkidks** [districtr/districtr#151]
When sharing or reloading the webpage on an NC congressional map, districtr has issues committing those changes. These issues appear when using any district (tested all of them), and affect VTDs in all of Buncombe (Asheville), parts of McDowell, and parts of Mecklenburg (Charlotte) county. Pictures of this issue can be found in this [imgur album](https://imgur.com/a/ftqPJjn).

**Comment by mapmeld** [comment]
Hi @Idkidks , we've fixed it! https://districtr.org/edit/1960

Thanks for catching this and documenting the problem.
It was an issue with how we stored VTDs with decimal numbers
