### ISSUE TITLE
Error in npm run develop

### ISSUE THREAD

**Issue by Sayan-Ghosh** [districtr/districtr#178]
I am getting the following error when I am trying to start the code base in local system.

[23:56:17] 'develop' errored after 44 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! districtr@0.0.1 develop: `gulp develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the districtr@0.0.1 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sayan/.npm/_logs/2020-03-25T18_26_18_014Z-debug.log

**Comment by mapmeld** [comment]
Hi - Can you check the version of these to make sure everything is up-to-date? In particular I know Ubuntu likes to install an older nodejs and npm unless you add the right PPA

```
make
gcc
node
npm
```

Then run
```npm install```
and see if all dependencies install correctly

**Comment by Sayan-Ghosh** [comment]
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

This worked. I actually got System limit for number of file watchers reached. This one solved it.
Thanks a lot.
