### ISSUE TITLE
404 errors on predrawn congressional maps

### ISSUE THREAD

**Issue by anatighe** [districtr/districtr#236]
Issue: Navigated to  `/wi/congress` to see the example of the existing congressional map and got a 404 error. 
Tried tx and ca, also getting the same error there. 

Steps to repro: clone repo, followed setup steps, started clicking around and ran into that issue.

**Comment by mapmeld** [comment]
Hi ! Thanks for documenting this - the ```deploy/_redirects``` file is loaded by Netlify and redirects that link. To test locally, you would do the redirect yourself, so ```http://localhost:3000/edit?url=/assets/wi-plans/congress.json#plan```

**Comment by anatighe** [comment]
Would it be helpful if I edited the Readme to add that? I haven't used Netlify before so it wasn't obvious to me.

**Comment by mapmeld** [comment]
That would be great, I would appreciate if you have suggestions for the readme based on your experience
